version: 2.1

executors:
  node:
    parameters:
      version:
        type: string
        default: lts
    docker:
      - image: circleci/node:<< parameters.version >>
    working_directory: ~/marp-vscode

commands:
  install:
    parameters:
      postinstall:
        type: steps
        default: []
    steps:
      - run: node --version
      - run: sudo npm install -g npm

      - restore_cache:
          keys:
            - v2.3-dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}-{{ .Branch }}
            - v2.3-dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}-
            - v2.3-dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-

      - run: npm ci
      - steps: << parameters.postinstall >>

      - save_cache:
          key: v2.3-dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}-{{ .Branch }}
          paths:
            - ~/.npm

  audit:
    steps:
      - checkout
      - install:
          postinstall:
            - run: npm run check:audit

  test:
    steps:
      - checkout
      - install

      - run:
          name: Prettier formatting
          command: npm run check:format

      - run:
          name: TypeScript type checking
          command: npm run check:ts

      - run:
          name: ESLint
          command: npm run lint:js

      - run:
          name: stylelint
          command: npm run lint:css

      - run:
          name: Jest
          command: npm run test:unit:coverage -- --ci --maxWorkers=2 --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: tmp/test-results

      - run: npx codecov

      - store_test_results:
          path: tmp/test-results

      - store_artifacts:
          path: ./coverage
          destination: coverage

jobs:
  audit:
    executor: node
    steps:
      - audit

  unit-electron9:
    executor:
      name: node
      version: '12.14.1'
    steps:
      - test

  unit-electron11:
    executor:
      name: node
      version: '12.18.3'
    steps:
      - test

  unit-electron12:
    executor:
      name: node
      version: '14.16.0'
    steps:
      - test

workflows:
  test:
    jobs:
      - audit
      - unit-electron9:
          requires:
            - audit
      - unit-electron11:
          requires:
            - audit
      - unit-electron12:
          requires:
            - audit
